// apps/web/src/routes/templates/new/+page.svelte
<script lang="ts">
	import type { Template } from '$lib/models/template.model';
	import Explainer from '$lib/components/Explainer.svelte';

	let template: Template = {
		fancyName: '',
		name: '',
		description: '',
		icon: '',
		image: '',
		versions: [],
		type: {
			type: 'DATABASE'
		}
	};
	let versions: string = '';

	function handleSubmit() {
		console.log('template', template);
	}
</script>

<div class="flex flex-1">
	<form class="flex flex-col flex-1 w-full h-full" on:submit|preventDefault={handleSubmit}>
		<div class="flex justify-between">
			<h1 class="font-bold text-lg">New Template</h1>

			<button class="btn btn-primary btn-sm">Save</button>
		</div>
		<div class="card flex-1 bg-base-300 w-full overflow-auto mt-4">
			<div class="card-body h-full max-h-0">
				<div class="flex flex-col gap-2">
					<div class="mt-2 grid grid-cols-2 items-center">
						<label for="fancyName" class="font-bold">Template name</label>
						<input
							name="fancyName"
							id="fancyName"
							class="input input-bordered w-full"
							bind:value={template.fancyName}
						/>
					</div>

					<div class="mt-2 grid grid-cols-2 items-center">
						<label for="name" class="font-bold">Internal name</label>
						<input
							name="name"
							id="name"
							class="input !bg-base-200 w-full"
							value={template.fancyName.replace(/ /g, '-').toLowerCase()}
							disabled
						/>
					</div>

					<div class="mt-2 grid grid-cols-2 items-center">
						<label for="template" class="font-bold">Image</label>
						<input
							name="image"
							id="image"
							class="input input-bordered w-full"
							bind:value={template.image}
						/>
					</div>

					<div class="mt-2 grid grid-cols-2 items-center">
						<div>
							<label for="description" class="font-bold">Versions</label>
							<Explainer
								explanation="Add versions separeated bya a comma(,). Example: '1.0, 1.1, 2.4'"
							/>
						</div>
						<input type="text" class="input input-bordered" bind:value={versions} />
					</div>

					<div class="mt-2 grid grid-cols-2 items-center">
						<label for="icon" class="font-bold">Icon (base64)</label>
						<input
							name="icon"
							id="icon"
							class="input input-bordered w-full"
							bind:value={template.icon}
						/>
					</div>

					<div class="mt-2 grid grid-cols-2 items-center">
						<label for="description" class="font-bold">Description</label>
						<textarea
							name="description"
							id="description"
							class="textarea textarea-bordered w-full"
							bind:value={template.description}
						/>
					</div>

					<div class="mt-2 grid grid-cols-2 items-center">
						<label for="description" class="font-bold">Type</label>
						<div class="dropdown w-full">
							<div tabindex="0" role="button" class="btn w-full justify-start">
								{template.type.type}
							</div>
							<ul class="dropdown-content z-[1] menu p-2 shadow bg-base-100 w-full rounded-box">
								<li><span class="p-2 hover:bg-base-200">DATABASE</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>

// frontend/src/app/routes/addons/new/new.component.ts
import {
  Component,
  Injector,
  OnInit,
  WritableSignal,
  signal,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Addon } from '../../../core/models/addon.model';
import { AddonService } from '../../../shared/services/addon.service';
import { CommonModule } from '@angular/common';
import {
  FormBuilder,
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { SidebarComponent } from '../../../shared/components/sidebar/sidebar.component';

@Component({
  selector: 'app-new',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, SidebarComponent],
  templateUrl: './new.component.html',
  styleUrl: './new.component.scss',
})
export class NewComponent implements OnInit {
  private name!: string;

  public addon: WritableSignal<Addon>;
  public selectedVersion: WritableSignal<string>;
  public form!: FormGroup;

  constructor(
    private addonService: AddonService,
    private route: ActivatedRoute,
    private fb: FormBuilder
  ) {
    this.addon = signal({} as Addon);
    this.selectedVersion = signal('latest');
    this.form = this.fb.group({
      name: ['', [Validators.required]],
      description: [''],
      image: ['', [Validators.required]],
      port: ['', [Validators.required]],
    });
  }

  ngOnInit(): void {
    this.name = this.route.snapshot.paramMap.get('name') || '';

    this.addonService.findByName(this.name).subscribe((data) => {
      this.addon.set(data);

      this.form.setValue({
        name: data.name,
        description: data.description,
        image: data.image,
        port: data.port,
      });

      data.envs.forEach((env) => {
        this.form.addControl(
          env.key,
          new FormControl(env.value, env.optional ? [] : [Validators.required])
        );
      });

      data.volumes.forEach((volume) => {
        this.form.addControl(
          volume.path,
          new FormControl(volume.path, [Validators.required])
        );
      });
    });
  }

  public deployAddon(): void {
    console.log('controls', {
      ...this.form.value,
      version: this.selectedVersion(),
    });
  }

  get f() {
    return this.form.controls;
  }
}

@defer (when addon()) {
<div class="flex flex-1 gap-2 w-full h-full p-2">
  <!-- Menu -->
  <ul class="menu bg-base-200 w-56 rounded-box">
    <li><a class="active">Configuration</a></li>
    <li><a href="{{ addon().infoUrl }}" target="_blank">Docs</a></li>
  </ul>

  <!-- Card -->
  <div class="card shadow bg-base-200 w-full h-full">
    <div class="card-body p-4 w-full h-full">
      <div class="flex justify-between items-center">
        <h2 class="card-title">{{ addon().fancyName }}</h2>

        <div class="flex gap-2">
          <button
            class="btn btn-primary btn-sm"
            (click)="deployAddon()"
            [disabled]="form.invalid"
          >
            Create
          </button>
        </div>
      </div>
      <div class="flex flex-col gap-2 mt-2 w-full h-full px-2 overflow-auto">
        <form [formGroup]="form" class="h-full max-h-0">
          <div class="mt-2 grid grid-cols-2 gap-2 items-center">
            <label for="name" class="font-bold">Name</label>
            <div class="flex flex-col">
              <input
                name="name"
                id="name"
                class="input input-bordered w-full"
                [ngClass]="{
                  'input-error': f['name'].touched && f['name'].errors
                }"
                formControlName="name"
              />
              @if (f['name'].touched && f['name'].errors) {
              <div class="label">
                <span class="text-error">Name is required</span>
              </div>
              }
            </div>
          </div>

          <div class="mt-2 grid grid-cols-2 items-center">
            <label for="description" class="font-bold">Description</label>
            <textarea
              name="description"
              id="description"
              class="textarea textarea-bordered w-full"
              formControlName="description"
            ></textarea>
          </div>

          <div class="mt-2 grid grid-cols-2 items-center">
            <label for="image" class="font-bold">Image</label>
            <input
              name="image"
              id="image"
              class="input input-bordered w-full"
              [value]="addon().image"
              disabled
            />
          </div>

          <div class="mt-2 grid grid-cols-2 items-center">
            <label for="version" class="font-bold">Version</label>
            <div class="dropdown">
              <div
                name="version"
                id="version"
                tabindex="0"
                role="button"
                class="btn btn-active justify-start w-full m-1"
              >
                {{ selectedVersion() }}
              </div>
              <ul
                tabindex="0"
                class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-full"
              >
                @for (version of addon().versions; track $index) {
                <li
                  [ngClass]="{
                    'bg-base-200 rounded-btn':
                      selectedVersion() === version.version
                  }"
                >
                  <a>{{ version.version }}</a>
                </li>
                }
              </ul>
            </div>
          </div>

          <div class="mt-2 grid grid-cols-2 items-center">
            <label for="name" class="font-bold">Port</label>
            <div class="flex flex-col">
              <input
                name="name"
                id="name"
                [ngClass]="{
                  'input-error': f['port'].touched && f['port'].errors
                }"
                class="input input-bordered w-full"
                type="number"
                formControlName="port"
              />
              @if (f['port'].touched && f['port'].errors) {
              <div class="label">
                <span class="text-error">Port is required</span>
              </div>
              }
            </div>
          </div>

          @if (addon().envs) {
          <div class="divider divider-start mt-12">
            <span class="font-bold text-xl">Env variables</span>
          </div>
          @for (env of addon().envs; track $index) {
          <div class="mt-2 grid grid-cols-2 items-center">
            <div class="flex items-end">
              <label for="env-{{ env.key }}" class="font-bold">{{
                env.key
              }}</label>

              <div class="dropdown dropdown-right">
                <div
                  tabindex="0"
                  role="button"
                  class="btn btn-circle btn-ghost btn-xs text-info"
                >
                  <svg
                    tabindex="0"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    class="w-4 h-4 stroke-current outline-none"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    ></path>
                  </svg>
                </div>
                <div
                  tabindex="0"
                  class="card compact dropdown-content z-[1] shadow bg-base-100 rounded-box w-64"
                >
                  <div tabindex="0" class="card-body">
                    <p>{{ env.explanation }}</p>
                  </div>
                </div>
              </div>

              @if (env.optional) {
              <span class="font-light italic">Optional</span>
              }
            </div>

            <div class="flex flex-col">
              <input
                name="env-{{ env.key }}"
                id="env-{{ env.key }}"
                [ngClass]="{
                  'input-error': f[env.key].touched && f[env.key].errors
                }"
                class="input input-bordered w-full"
                formControlName="{{ env.key }}"
              />
              @if (f[env.key].touched && f[env.key].errors) {
              <div class="label">
                <span class="text-error">{{ env.key }} is required</span>
              </div>
              }
            </div>
          </div>
          } } @if (addon().volumes) {
          <div class="divider divider-start mt-12">
            <span class="font-bold text-xl">Volumes</span>
          </div>
          @for (volume of addon().volumes; track $index) {
          <div class="mt-2 grid grid-cols-2 items-center">
            <label for="env-{{ volume.path }}" class="font-bold">{{
              volume.path
            }}</label>
            <div class="flex flex-col">
              <input
                name="env-{{ volume.path }}"
                id="env-{{ volume.path }}"
                [ngClass]="{
                  'input-error': f[volume.path].touched && f[volume.path].errors
                }"
                class="input input-bordered w-full"
                formControlName="{{ volume.path }}"
              />
              @if (f[volume.path].touched && f[volume.path].errors) {
              <div class="label">
                <span class="text-error">{{ volume.path }} is required</span>
              </div>
              }
            </div>
          </div>
          } }
        </form>
      </div>
    </div>
  </div>
</div>
} @loading {
<span class="loading loading-spinner text-secondary"></span>
}
