// apps/frontend/src/app/modules/deployments/new/new.component.ts
import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ButtonComponent } from '../../../components/button/button.component';
import { CardComponent } from '../../../components/card/card.component';
import { CommonModule } from '@angular/common';
import { DeploymentService } from '../../../services/deployment.service';
import { DeploymentVolume } from '../../../models/deployment-volume.model';
import { DeploymentEnv } from '../../../models/deploymentenv.model';

@Component({
  selector: 'app-new',
  standalone: true,
  imports: [CardComponent, ButtonComponent, ReactiveFormsModule, CommonModule],
  templateUrl: './new.component.html',
  styleUrl: './new.component.css'
})
export class NewComponent implements OnInit {
  public form!: FormGroup;

  constructor(private deploymentService: DeploymentService, private fb: FormBuilder) {}

  ngOnInit(): void {
    this.form = this.fb.group({
      name: ['', [Validators.required]],
      image: ['', [Validators.required]],
      replicas: [1, [Validators.required, Validators.min(1)]],
      memory: ['256', [Validators.required, Validators.min(256)]],
      cpu: ['500', [Validators.required, Validators.min(500)]],
      exposedNetwork: [false, [Validators.required]],
      port: [80, [Validators.required]],
      env: this.fb.array([]),
      volumes: this.fb.array([])
    });
  }

  addEnvField(): void {
    this.env.push(this.createEnvField());
  }

  removeEnvField(index: number): void {
    this.env.removeAt(index);
  }

  addVolumeField(): void {
    this.volumes.push(this.createVolumeField());
  }

  removeVolumeField(index: number): void {
    this.volumes.removeAt(index);
  }

  handleSubmit() {
    const envValues: DeploymentEnv[] = [];
    Object.values(this.env.value).forEach((value: unknown) => {
      envValues.push({
        key: (value as { key: string; value: string }).key,
        value: (value as { key: string; value: string }).value
      });
    });

    const volumeValues: DeploymentVolume[] = [];
    Object.values(this.volumes.value).forEach((value: unknown) => {
      volumeValues.push({
        path: (value as { path: string; size: string }).path,
        size: (value as { path: string; size: string }).size,
        accessMode: 'ReadWriteOnce'
      });
    });

    this.deploymentService
      .create({
        name: this.f['name'].value,
        description: '',
        image: this.f['image'].value,
        replicas: this.f['replicas'].value,
        memory: String(this.f['memory'].value),
        cpu: this.f['cpu'].value,
        exposedNetwork: this.f['exposedNetwork'].value,
        port: this.f['port'].value,
        envs: envValues,
        volumes: volumeValues
      })
      .subscribe((data) => {
        console.log('data', data);
      });
  }

  get env(): FormArray {
    return <FormArray>this.form.get('env');
  }

  get volumes(): FormArray {
    return <FormArray>this.form.get('volumes');
  }

  get f() {
    return this.form.controls;
  }

  /* private methods */
  private createEnvField(): FormGroup {
    return this.fb.group({
      key: [null, Validators.required],
      value: [null, Validators.required]
    });
  }

  private createVolumeField(): FormGroup {
    return this.fb.group({
      path: [null, Validators.required],
      size: [null, Validators.required]
    });
  }
}

<div class="flex flex-col flex-1 w-full h-full sm:px-6 overflow-hidden">
  <h1 class="font-semibold text-xl">New deployment</h1>

  <div class="flex flex-col gap-2 mt-8 overflow-auto">
    <div class="card bg-base-200 overflow-auto">
      <div class="card-body">
        <form [formGroup]="form" (ngSubmit)="handleSubmit()">
          <div class="grid gap-8">
            <div>
              <h2 class="text-lg font-semibold">Basic Information</h2>
              <div class="grid gap-4 mt-4">
                <!-- Name input group -->
                <div class="form-control w-full">
                  <div class="label">
                    <label for="deployment-name" class="label-text">Deployment name</label>
                  </div>
                  <input
                    type="text"
                    id="deployment-name"
                    class="input input-bordered w-full"
                    [ngClass]="{
                      'input-error': form.get('name')?.touched && form.get('name')?.invalid
                    }"
                    formControlName="name"
                    placeholder="My very cool deployment"
                  />
                  @if (form.get('name')?.touched && form.get('name')?.invalid) {
                  <div class="label">
                    <span class="label-text-alt text-error">This field is required</span>
                  </div>
                  }
                </div>
                <!-- Image input group -->
                <div class="form-control w-full">
                  <div class="label">
                    <label for="image-name" class="label-text">Image name</label>
                  </div>
                  <input
                    type="text"
                    id="image-name"
                    class="input input-bordered w-full"
                    [ngClass]="{
                      'input-error': form.get('image')?.touched && form.get('image')?.invalid
                    }"
                    formControlName="image"
                    placeholder="nginx:latest"
                  />
                  @if (form.get('image')?.touched && form.get('image')?.invalid) {
                  <div class="label">
                    <span class="label-text-alt text-error">This field is required</span>
                  </div>
                  }
                </div>
              </div>
            </div>

            <div class="divider my-0"></div>

            <div>
              <h2 class="text-lg font-semibold">Scaling Options</h2>
              <!-- Replicas input group -->
              <div class="form-control w-full">
                <div class="label">
                  <label for="replicas" class="label-text">Replicas</label>
                </div>
                <input
                  type="number"
                  min="1"
                  step="1"
                  id="replicas"
                  class="input input-bordered w-full"
                  [ngClass]="{
                    'input-error': form.get('replicas')?.touched && form.get('replicas')?.invalid
                  }"
                  formControlName="replicas"
                />
                @if (form.get('replicas')?.touched && form.get('replicas')?.invalid) {
                <div class="label">
                  <span class="label-text-alt text-error">This field is required</span>
                </div>
                }
              </div>

              <!-- Memory input group -->
              <div class="form-control w-full">
                <div class="label">
                  <label for="memory" class="label-text">Memory</label>
                </div>
                <input
                  type="number"
                  min="256"
                  step="256"
                  id="memory"
                  class="input input-bordered w-full"
                  [ngClass]="{
                    'input-error': form.get('memory')?.touched && form.get('memory')?.invalid
                  }"
                  formControlName="memory"
                />
                @if (form.get('memory')?.touched && form.get('memory')?.invalid) {
                <div class="label">
                  <span class="label-text-alt text-error">This field is required</span>
                </div>
                }
              </div>

              <!-- Cpu input group -->
              <div class="form-control w-full">
                <div class="label">
                  <label for="cpu" class="label-text">Cpu</label>
                </div>
                <input
                  type="number"
                  min="500"
                  step="500"
                  id="cpu"
                  class="input input-bordered w-full"
                  [ngClass]="{
                    'input-error': form.get('cpu')?.touched && form.get('cpu')?.invalid
                  }"
                  formControlName="cpu"
                />
                @if (form.get('cpu')?.touched && form.get('cpu')?.invalid) {
                <div class="label">
                  <span class="label-text-alt text-error">This field is required</span>
                </div>
                }
              </div>
            </div>

            <div class="divider my-0"></div>

            <div>
              <h2 class="text-lg font-semibold">Advanced Settings</h2>
              <div class="grid gap-4 mt-4">
                <!-- Exposed input group -->
                <div class="form-control w-full">
                  <div class="label">
                    <label for="exposedNetwork" class="label-text">Expose to network</label>
                  </div>
                  <input
                    type="checkbox"
                    min="500"
                    step="500"
                    id="exposedNetwork"
                    class="toggle"
                    [ngClass]="{
                      'input-error':
                        form.get('exposedNetwork')?.touched && form.get('exposedNetwork')?.invalid
                    }"
                    formControlName="exposedNetwork"
                  />
                  @if (form.get('exposedNetwork')?.touched && form.get('exposedNetwork')?.invalid) {
                  <div class="label">
                    <span class="label-text-alt text-error">This field is required</span>
                  </div>
                  }
                </div>

                <!-- Port input group -->
                <div class="form-control w-full">
                  <div class="label">
                    <label for="port" class="label-text">Port</label>
                  </div>
                  <input
                    type="number"
                    id="port"
                    class="input input-bordered w-full"
                    [ngClass]="{
                      'input-error': form.get('port')?.touched && form.get('port')?.invalid
                    }"
                    formControlName="port"
                  />
                  @if (form.get('port')?.touched && form.get('port')?.invalid) {
                  <div class="label">
                    <span class="label-text-alt text-error">This field is required</span>
                  </div>
                  }
                </div>

                <!-- Env variables inputs group -->
                <div class="flex flex-col gap-2">
                  <h1>Environment variables</h1>
                  <div formArrayName="env" class="flex flex-col gap-2">
                    @for (envField of env.controls; track envField; let indx = $index) {
                    <div [formGroupName]="indx" class="grid grid-cols-7 items-end gap-2">
                      <div class="form-control w-full col-span-3">
                        <div class="label">
                          <label for="key" class="label-text">ENV_VARIABLE_KEY</label>
                        </div>
                        <input
                          id="key"
                          type="text"
                          aria-describedby="key"
                          formControlName="key"
                          class="input input-bordered w-full"
                        />
                      </div>

                      <div class="form-control w-full col-span-3">
                        <div class="label">
                          <label for="value" class="label-text">ENV_VARIABLE_VALUE</label>
                        </div>
                        <input
                          id="value"
                          type="text"
                          aria-describedby="value"
                          formControlName="value"
                          class="input input-bordered w-full"
                        />
                      </div>

                      <button type="button" class="btn btn-error" (click)="removeEnvField(indx)">
                        -
                      </button>
                    </div>
                    }
                  </div>

                  <button type="button" class="btn btn-secondary w-52" (click)="addEnvField()">
                    Add
                  </button>
                </div>

                <!-- Volumes inputs group -->
                <div class="flex flex-col gap-2">
                  <h1>Volumes</h1>
                  <div formArrayName="volumes" class="flex flex-col gap-2">
                    @for (volField of volumes.controls; track volField; let indx = $index) {
                    <div [formGroupName]="indx" class="grid grid-cols-7 items-end gap-2">
                      <div class="form-control w-full col-span-3">
                        <div class="label">
                          <label for="path" class="label-text">Volume path</label>
                        </div>
                        <input
                          id="path"
                          type="text"
                          aria-describedby="path"
                          formControlName="path"
                          class="input input-bordered w-full"
                        />
                      </div>

                      <div class="form-control w-full col-span-3">
                        <div class="label">
                          <label for="size" class="label-text">Size</label>
                        </div>
                        <input
                          id="size"
                          type="text"
                          aria-describedby="size"
                          formControlName="size"
                          class="input input-bordered w-full"
                        />
                      </div>

                      <button type="button" class="btn btn-error" (click)="removeVolumeField(indx)">
                        -
                      </button>
                    </div>
                    }
                  </div>

                  <button type="button" class="btn btn-secondary w-52" (click)="addVolumeField()">
                    Add
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div class="mt-4">
            <button type="submit" class="btn btn-primary btn-block" [disabled]="form.invalid">
              Create
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

// apps/web/src/routes/applications/new/+page.svelte
<script lang="ts">
	import { env } from '$env/dynamic/public';
	import type { ApplicationEnv, ApplicationVolume } from '$lib/models/application.model';
	import { forms, validators, maxLength, required, minLength, number } from 'ui';

	const form = forms({
		name: { validators: [required, maxLength(30)] },
		image: { validators: [required] },
		replicas: {
			initial: '1',
			validators: [required, minLength(1), number]
		},
		memory: {
			initial: '128',
			validators: [required, number]
		},
		cpu: {
			initial: '100',
			validators: [required, number]
		}
	});

	// DATA
	let envInputs: {
		key: string;
		value: string;
	}[] = [];
	let volumeInputs: {
		key: string;
		size: string;
	}[] = [];

	// FUNCTIONS
	function addEnvInput() {
		envInputs = [...envInputs, { key: '', value: '' }];
	}

	function removeEnvInput(index: number) {
		envInputs.splice(index, 1);
		envInputs = [...envInputs];
	}

	function addVolumeInput() {
		volumeInputs = [...volumeInputs, { key: '', size: '' }];
	}

	function removeVolumeInput(index: number) {
		volumeInputs.splice(index, 1);
		volumeInputs = [...volumeInputs];
	}

	async function handleForm() {
		const updatedEnvs: ApplicationEnv = {} as ApplicationEnv;
		let currentKeyEnv: string;
		Object.entries($form.values).map(([key, value]) => {
			if (key.includes('env-key-')) currentKeyEnv = value!;
			if (key.includes('env-value-')) updatedEnvs[currentKeyEnv] = value!;
		});

		const updatedvolumes: ApplicationVolume[] = [];
		let currentKeyVolume: string;
		Object.entries($form.values).map(([key, value]) => {
			if (key.includes('volume-key-')) currentKeyVolume = value!;
			if (key.includes('volume-size-')) {
				updatedvolumes.push({
					path: currentKeyVolume,
					size: Number(value!),
					accessMode: ['ReadWriteOnce']
				});
			}
		});

		const result = await fetch(`${env.PUBLIC_API_URL}/applications/create`, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({
				namespace: 'default',
				name: $form.name.value,
				description: '',
				image: $form.image.value,
				replicas: $form.replicas.value,
				cpu: $form.cpu.value,
				memory: $form.memory.value,
				env: updatedEnvs,
				volumes: updatedvolumes
			})
		});
		const data = await result.json();
		console.log('data', data);
	}
</script>

<div class="flex flex-col w-full overflow-auto">
	<div class="max-h-0">
		<h1 class="font-semibold text-xl">New application</h1>

		<form use:form on:submit|preventDefault={handleForm}>
			<div class="card bg-base-300 shadow mt-4 w-full">
				<div class="card-body px-4 py-4">
					<h1 class="card-title text-base">Name</h1>

					<div class="flex flex-col w-full">
						<label class="form-control w-full">
							<input
								name="name"
								type="text"
								placeholder="Type here"
								class="input input-bordered w-full"
								class:input-error={$form.name?.touched &&
									Object.keys($form.name?.errors).length > 0}
							/>
							<div class="label flex-col">
								{#if $form.name?.touched && Object.keys($form.name?.errors).length > 0}
									<span class="label-text-alt font-thin text-error w-full">
										{#if $form.name?.errors.required}
											Name is required
										{:else}
											Name max lenght is 30 characters
										{/if}
									</span>
								{/if}
								<span class="label-text-alt font-thin self-baseline"
									>Choose a descriptive name for this application. Must be between 1-30 characters
									and consist of alphabets (A-Z a-z), numbers (0-9) and spaces ( ).</span
								>
							</div>
						</label>
					</div>
				</div>
			</div>

			<div class="card bg-base-300 shadow mt-4 w-full">
				<div class="card-body px-4 py-4">
					<h1 class="card-title text-base">Image registry</h1>

					<div class="flex flex-col w-full">
						<div class="form-control w-full">
							<div class="dropdown">
								<div tabIndex={0} role="button" class="btn bg-base-100 m-1">Docker Hub</div>
								<ul
									tabIndex={0}
									class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52"
								>
									<li class="hover:bg-base-300"><div class="p-2">Docker Hub</div></li>
								</ul>
							</div>
							<div class="label">
								<span class="label-text-alt font-thin"
									>Application image will be pulled from this registry. Currently only Docker
									registry is supported.</span
								>
							</div>
						</div>
					</div>

					<div class="divider" />

					<h1 class="card-title text-base">Image name</h1>
					<div class="flex flex-col w-full">
						<label class="form-control w-full">
							<input
								name="image"
								type="text"
								placeholder="Type here"
								class="input input-bordered w-full"
								class:input-error={$form.image?.touched &&
									Object.keys($form.image?.errors).length > 0}
							/>
							<div class="label flex-col text-left">
								{#if $form.image?.touched && Object.keys($form.image?.errors).length > 0}
									<span class="label-text-alt font-thin text-error w-full">
										{#if $form.image?.errors.required}
											Image name is required
										{/if}
									</span>
								{/if}
								<span class="label-text-alt font-thin w-full"
									>Name of the image to pull. Tag will be selected later when making a deployment.</span
								>
							</div>
						</label>
					</div>
				</div>
			</div>

			<div class="card bg-base-300 shadow mt-4 w-full">
				<div class="card-body px-4 py-4">
					<h1 class="card-title text-base">Environment variables</h1>

					<div class="card-actions">
						<button
							on:click={addEnvInput}
							type="button"
							class="btn btn-ghost bg-base-100 border border-base-300"
							>Add environment variable</button
						>
					</div>
					<div class="flex flex-col gap-2 w-full">
						{#each envInputs as envInput, index}
							<div class="flex items-center gap-2">
								<input
									name={`env-key-${index}`}
									type="text"
									class="input input-bordered"
									class:input-error={$form[`env-key-${index}`]?.touched &&
										Object.keys($form[`env-key-${index}`]?.errors || []).length > 0}
									use:validators={[required]}
									bind:value={envInput.key}
								/>
								<input
									name={`env-value-${index}`}
									type="text"
									class="input input-bordered"
									class:input-error={$form[`env-value-${index}`]?.touched &&
										Object.keys($form[`env-value-${index}`]?.errors || []).length > 0}
									use:validators={[required]}
									bind:value={envInput.value}
								/>

								<button on:click={() => removeEnvInput(index)} type="button" class="btn bg-base-100"
									>X</button
								>
							</div>
						{/each}
					</div>
				</div>
			</div>

			<div class="card bg-base-300 shadow mt-4 w-full">
				<div class="card-body px-4 py-4">
					<h1 class="card-title text-base">Volumes</h1>

					<div class="card-actions">
						<button
							on:click={addVolumeInput}
							type="button"
							class="btn btn-ghost bg-base-100 border border-base-300">Add volume</button
						>
					</div>
					<div class="flex flex-col gap-2 w-full">
						{#each volumeInputs as volumeInput, index}
							<div class="flex items-center gap-2">
								<input
									name={`volume-key-${index}`}
									type="text"
									class="input input-bordered"
									placeholder="Container volume"
									class:input-error={$form[`volume-key-${index}`]?.touched &&
										Object.keys($form[`env-key-${index}`]?.errors || []).length > 0}
									use:validators={[required]}
									bind:value={volumeInput.key}
								/>

								<input
									name={`volume-size-${index}`}
									type="number"
									class="input input-bordered"
									placeholder="Size(Mb)"
									class:input-error={$form[`volume-size-${index}`]?.touched &&
										Object.keys($form[`volume-size-${index}`]?.errors || []).length > 0}
									use:validators={[required]}
									bind:value={volumeInput.size}
								/>

								<button
									on:click={() => removeVolumeInput(index)}
									type="button"
									class="btn bg-base-100">X</button
								>
							</div>
						{/each}
					</div>
				</div>
			</div>

			<div class="card bg-base-300 shadow mt-4 w-full">
				<div class="card-body px-4 py-4">
					<h1 class="card-title text-base">Replicas</h1>

					<div class="flex items-center gap-2">
						<input
							name="replicas"
							type="number"
							class="input input-bordered w-24"
							use:validators={[required]}
							bind:value={$form.replicas.value}
						/>

						<div class="join join-horizontal">
							<button
								on:click={() => ($form.replicas.value = '1')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.replicas.value === '1'}>1</button
							>
							<button
								on:click={() => ($form.replicas.value = '2')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.replicas.value === '2'}>2</button
							>
							<button
								on:click={() => ($form.replicas.value = '3')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.replicas.value === '3'}>3</button
							>
							<button
								on:click={() => ($form.replicas.value = '4')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.replicas.value === '4'}>4</button
							>
							<button
								on:click={() => ($form.replicas.value = '5')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.replicas.value === '5'}>5</button
							>
							<button
								on:click={() => ($form.replicas.value = '10')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.replicas.value === '10'}>10</button
							>
						</div>
					</div>

					<div class="divider" />

					<h1 class="card-title text-base">Memory (mb)</h1>

					<div class="flex items-center gap-2">
						<div class="join">
							<input
								name="memory"
								type="number"
								class="input input-bordered w-24"
								use:validators={[required]}
								bind:value={$form.memory.value}
							/>
							<!-- <div class="flex items-center justify-center bg-base-300 p-2 join-item">Mb</div> -->
						</div>

						<div class="join join-horizontal">
							<button
								on:click={() => ($form.memory.value = '128')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.memory.value === '128'}>128</button
							>
							<button
								on:click={() => ($form.memory.value = '256')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.memory.value === '256'}>256</button
							>
							<button
								on:click={() => ($form.memory.value = '512')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.memory.value === '512'}>512</button
							>
							<button
								on:click={() => ($form.memory.value = '768')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.memory.value === '768'}>768</button
							>
							<button
								on:click={() => ($form.memory.value = '1024')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.memory.value === '1024'}>1024</button
							>
							<button
								on:click={() => ($form.memory.value = '2048')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.memory.value === '2048'}>2048</button
							>
						</div>
					</div>

					<div class="divider" />

					<h1 class="card-title text-base">Cpu (mcpu)</h1>

					<div class="flex items-center gap-2">
						<div class="join">
							<input
								name="cpu"
								type="number"
								class="input input-bordered w-24"
								use:validators={[required]}
								bind:value={$form.cpu.value}
							/>
							<!-- <div class="flex items-center justify-center bg-base-300 p-2 join-item">mcpu</div> -->
						</div>

						<div class="join join-horizontal">
							<button
								on:click={() => ($form.cpu.value = '100')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.cpu.value === '100'}>100</button
							>
							<button
								on:click={() => ($form.cpu.value = '250')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.cpu.value === '250'}>250</button
							>
							<button
								on:click={() => ($form.cpu.value = '500')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.cpu.value === '500'}>500</button
							>
							<button
								on:click={() => ($form.cpu.value = '750')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.cpu.value === '750'}>750</button
							>
							<button
								on:click={() => ($form.cpu.value = '1000')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.cpu.value === '1000'}>1000</button
							>
							<button
								on:click={() => ($form.cpu.value = '2000')}
								type="button"
								class="btn btn-secondary join-item"
								class:bg-primary={$form.cpu.value === '2000'}>2000</button
							>
						</div>
					</div>
				</div>
			</div>

			<button type="submit" class="btn btn-block btn-secondary mt-4" disabled={!$form.valid}
				>Create application</button
			>
		</form>
	</div>
</div>
