// frontend/src/app/routes/addons/addons.component.ts
import { Component, Injector, OnInit, Signal, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';

import { Addon } from '../../core/models/addon.model';
import { AddonService } from '../../shared/services/addon.service';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-addons',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './addons.component.html',
  styleUrl: './addons.component.scss',
})
export class AddonsComponent implements OnInit {
  public addons!: Signal<Addon[]>;

  constructor(private addonService: AddonService, private injector: Injector) {}

  ngOnInit(): void {
    this.addons = toSignal(this.addonService.findAll(), {
      initialValue: [],
      injector: this.injector,
    });
  }
}

@defer (when addons()) {
<div class="flex flex-1">
  <div
    class="grid grid-flow-rows grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 mt-4"
  >
    @for (addon of addons(); track $index) {
    <div
      class="card bg-base-200 shadow-sm cursor-pointer hover:shadow"
      routerLink="/addons/new/{{ addon.name }}"
    >
      <div class="card-body justify-center items-center">
        <div class="avatar">
          <div class="w-24 rounded">
            <img
              src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg"
            />
          </div>
        </div>
        <div class="card-title justify-center">{{ addon.fancyName }}</div>
        <div>
          <p class="font-thin text-wrap text-ellipsis">
            {{ addon.description }}
          </p>
        </div>
      </div>
    </div>
    }
  </div>
</div>
} @loading {
<div class="flex flex-1">
  <span class="loading loading-spinner text-secondary"></span>
</div>
}

// apps/web/src/routes/addons/+page.svelte
<script lang="ts">
	import type { Addon } from '$lib/models/addon.model';
	import type { PageDataResponse } from '$lib/models/api.model';

	export let data: PageDataResponse<Addon[]>;

	const { data: addons } = data;
	console.log('addons', addons);
</script>

<div class="flex-col justify-center">
	<div class="flex flex-col">
		<div class="flex justify-between">
			<h1 class="text-2xl font-bold">Addons</h1>
			<a href="/addons/new" class="btn btn-primary btn-sm">+ Add</a>
		</div>
		<div
			class="grid grid-flow-rows grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 mt-4"
		>
			{#each addons as addon}
				<a
					href={`/addons/deploy/${addon.name}`}
					class="card shadow bg-base-200 text-base-content hover:scale-105"
				>
					<div class="card-body p-4">
						<div class="flex flex-col items-center">
							<div class="flex flex-1 items-center gap-2">
								<img src={addon.icon} alt={`${addon.name} icon`} class="h-10 w-10" />
								<h1 class="font-bold text-xl">{addon.fancyName}</h1>
							</div>
							<p class="mt-2 text-sm font-thin text-ellipsis text-center">{addon.description}</p>
						</div>
					</div>
				</a>
			{/each}
		</div>
	</div>
</div>
